DataInnovation/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth.views import LogoutView
from django.views.generic import RedirectView

from accounts.views import LoginView, RegisterView

from home import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.home, name='home_url'),
    url(r'^news/$', views.NewsView.as_view(), name='news_url'),
    path('news/<int:pk>/', views.NewsDetailView.as_view()),
    path('news/<int:pk>/delete/', views.NewsDelete.as_view()),
    url(r'^news/create$', views.NewsRegisterView.as_view(), name='create_news'),
    path('news/<int:pk>/edit/', views.NewsDetailUpdateView.as_view(), name='edit_news'),
    path('news/<int:pk>/delete/', views.NewsDelete.as_view(), name='delete_news'),

    path('about/',include('home.urls')),
    
    url(r'^accounts/login/', RedirectView.as_view(url='/login')),
    url(r'^account/', include('accounts.urls', namespace='account')),
    url(r'^account/', include('accounts.passwords.urls')),

    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),

    url(r'^contact/', views.contact, name='contact'),  
    
] 


# if settings.DEBUG:c
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    
    url(r'^$', views.about, name='about_url'),
    url(r'^vision/', views.vision, name='vision_url'),
    url(r'^history/', views.history, name='history_url'),

    # path('<slug:element>/', views.AboutView.as_view()), # Overview of content
    # path('<slug:element>/<int:pk>/', views.AboutDetailView.as_view()), # Detail View of content
    
    url(r'^team/create/$', views.TeamRegisterView.as_view(), name='create_team'),
    path('team/', views.TeamView.as_view(), name='team_url'), # Detail View of content
    path('team/<int:pk>/', views.TeamDetailView.as_view(), name='team_detail'), # Detail View of content
    path('team/<int:pk>/edit', views.TeamDetailUpdateView.as_view(), name='edit_team'),
    path('team/<int:pk>/delete/', views.TeamDelete.as_view(), name='delete_team'),

    url(r'^solution/create$', views.SolutionRegisterView.as_view(), name='create_solution'),
    path('solution/', views.SolutionView.as_view(), name='solution_url'), # Detail View of content
    path('solution/<int:pk>/', views.SolutionDetailView.as_view(), name='solution_detail'), # Detail View of content
    path('solution/<int:pk>/edit', views.SolutionDetailUpdateView.as_view(), name='edit_solution'),
    path('solution/<int:pk>/delete/', views.SolutionDelete.as_view(), name='delete_solution'),

    url(r'^partner/create$', views.PartnerRegisterView.as_view(), name='create_partner'),
    path('partner/', views.PartnerView.as_view(), name='partner_url'), # Detail View of content
    path('partner/<int:pk>/', views.PartnerDetailView.as_view(), name='partner_detail'), # Detail View of content
    path('partner/<int:pk>/edit', views.PartnerDetailUpdateView.as_view(), name='edit_partner'),
    path('partner/<int:pk>/delete/', views.PartnerDelete.as_view(), name='delete_partner'),

    url(r'^award/create$', views.AwardRegisterView.as_view(), name='create_award'),
    path('award/', views.AwardView.as_view(), name='award_url'), # Detail View of content
    path('award/<int:pk>/', views.AwardDetailView.as_view(), name='award_detail'), # Detail View of content
    path('award/<int:pk>/edit', views.AwardDetailUpdateView.as_view(), name='edit_award'),
    path('award/<int:pk>/delete/', views.AwardDelete.as_view(), name='delete_award'),

]


# account/email/confirm/asdasfd/ -> activaiton view

templates/about/about-cards.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>{{ title }}</h2>
{% if user.is_authenticated %}
    {% include 'base/admin_create.html' %}
{% endif %}
{% if object_list %}
    {% for member in object_list %}
        {% if member.featured and member.display %}
        <div class='row'>
            <div class='col'>
                <div class="card fluid mb-3">
                    {% include 'about/snippets/member-card.html' %}
                </div>
            </div>
        </div><br>
        {% endif %}
    {% endfor %}
    <div class='row'>
        {% for member in object_list %}
            {% if not member.featured and member.display %}
                {% if team %}
                <div class='col col-6 mb-3'>
                {% else %}
                <div class='col col-md-6 col-lg-4 mb-3'>
                {% endif %}
                    <div class="card">
                        {% include 'about/snippets/member-card.html' %}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    {% if user.is_authenticated %}
        <div class='row px-3'>
            Cards currently hidden:
        </div>
        <div class='row'>
            {% for member in object_list %}
                {% if not member.display %}
                   <div class='col col-md-6 col-lg-4 mb-3'>
                        <div class="card">
                            {% if member.featured %}
                                Featured Card
                            {% endif %}
                            {% include 'about/snippets/member-card.html' %}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}
{% else %}
    Uh-oh...
    {% comment %} {% include 'about/snippets/about.html' %} {% endcomment %}
{% endif %}
{% endblock %}

templates/about/about-detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class='row'>
        <div class='col px-5'>
            <div class="card mb-3 border-white">
                <div class="row no-gutters m-auto">
                    {% if team %}
                        <div class="col-md-6 col-lg-4 text-center my-5">
                    {% else %}
                        <div class="col text-center">
                    {% endif %}
                        {% if object.image %}
                            <img src="{{ object.image.url }}" class="card-img-top" alt="..." style="max-height:350px; width:auto;">
                        {% else %}
                            <img src="{% static 'img/DIAILogo1.png' %}" class="card-img-top" alt="..." style="max-height:350px; width:auto;">
                        {% endif %}
                    </div>
                    {% if team %}
                    <div class="col-md-6 col-lg-7">
                    {% else %}
                    <div>
                    {% endif %}
                        <div class="card-body">
                            <h1 class="card-title">{% if object.title %}{{ object.title|safe }}{% else %}{{ object.name }}{% endif %}</h1>
                            {% if object.role %}
                                <h5 class='card-title'>{{ object.role }}</h5>
                            {% endif %}
                            {% if object.solution %}
                                <h5 class='card-title'>{{object.solution}}</h5>
                            {% endif %}
                            <p class="card-text">
                            {{ object.summary }}</br> </br>
                            </p>

                            {% comment %} <div class='row'>
                                <div class='col'>
                                {% if object.about == object.about|striptags %}  
                                    {{ object.about|linebreaks }}
                                {% else %}
                                    {{ object.about|safe }}
                                {% endif %}
                                </div>
                            </div> {% endcomment %}
                             {% comment %} <div class='row'>
                                <div class='col px-5 m-auto'>
                                {% if object.email %} 
                                    <a href="mailto:{{ object.email }}" class="scl-btn shadow fas fa-envelope"></a>
                                {% endif %}
                                {% if object.website %} 
                                    <a href="{{ object.website }}" class="scl-btn shadow fas fa-globe"></a>
                                {% endif %}
                                {% if object.linkedin %} 
                                    <a href="{{ object.linkedin }}" class="scl-btn shadow fab fa-linkedin-in"></a>
                                {% endif %}
                            </div> {% endcomment %}
                        </div>
                    </div>
                </div>
            </div>    
        </div>
    </div>
    <div class='row'>
        <div class='col px-5 m-auto'>
        {% if object.about == object.about|striptags %}  
            {{ object.about|linebreaks }}
        {% else %}
            {{ object.about|safe }}
        {% endif %}
        </div>
    </div> 
    <div class='row'>
        <div class='col px-5 m-auto'>
        {% if object.email %} 
            <a href="mailto:{{ object.email }}" class="scl-btn shadow fas fa-envelope"></a>
        {% endif %}
        {% if object.website %} 
            <a href="{{ object.website }}" class="scl-btn shadow fas fa-globe"></a>
        {% endif %}
        {% if object.linkedin %} 
            <a href="{{ object.linkedin }}" class="scl-btn shadow fab fa-linkedin-in"></a>
        {% endif %}
    </div>
{% endblock %}

templates/about/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2>{{ title }}</h2>
<div class='row row-cols-md-3'>
    <div class='card-deck'>
        <div class='col p-3 col-md-6 col-lg-4'>
            <div class="card">
                <img src="{% static 'img/DIAILogo1.png' %}" class="card-img-top p-3" alt="vision.png" style="max-width: 100%; height:auto;">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'about:vision_url' %}" class="card-link">Our Vision</a></h5>
                    <h6 class="card-subtitle mb-2 text-muted">Read about what we want to do for you</h6>
                    <p class="card-text">We want to help you make difficult business the right business decision when faced with complex parameters.</p>
                    {% comment %} Click here to read more about us! {% endcomment %}
                </div>
            </div>
        </div>
        
        <div class='col p-3 col-md-6 col-lg-4'>
            <div class="card">
                <img src="{% static 'img/team.png' %}" class="card-img-top p-3" alt="team.png">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'about:team_url' %}" class="card-link">Our Team</a></h5>
                    <h6 class="card-subtitle mb-2 text-muted">Come and meet our team</h6>
                    <p class="card-text">We have many personal achievements that we are proud to share to give you an idea of our expertise.</p>
                    {% comment %} Click here to see the team! {% endcomment %}
                </div>
            </div>
        </div>

        <div class='col p-3 col-md-6 col-lg-4'>
            <div class="card">
                <img src="{% static 'img/solutions.png' %}" class="card-img-top p-3" alt="solutions.png">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'about:solution_url' %}" class="card-link">Our Solutions</a></h5>
                    <h6 class="card-subtitle mb-2 text-muted">These are our business solutions</h6>
                    <p class="card-text">We have used the recent advancements in AI and Machine Learning to develop applications that find the best solutions.</p>
                    {% comment %} Click here to read more about our apps! {% endcomment %}
                </div>
            </div>
        </div>

        <div class='col p-3 col-md-6 col-lg-4'>
            <div class="card">
                <img src="{% static 'img/history.png' %}" class="card-img-top p-3" alt="history.png">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'about:history_url' %}" class="card-link">Our History</a></h5>
                    <h6 class="card-subtitle mb-2 text-muted">Read about how we came to be</h6>
                    <p class="card-text">The path of the entrepenuer starting a business in a complex world.</p>
                    {% comment %} Click here to read about our company! {% endcomment %}
                </div>
            </div>
        </div>

        <div class='col p-3 col-md-6 col-lg-4'>
            <div class="card">
                <img src="{% static 'img/awards.png' %}" class="card-img-top p-3" alt="awards.png">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'about:award_url' %}" class="card-link">Our Awards</a></h5>
                    <h6 class="card-subtitle mb-2 text-muted">Read about the achievments and awards we have won</h6>
                    <p class="card-text">Our ingenuity and success has granted us many awards and contracts.</p>
                    {% comment %} Click here to read about some of our past projects! {% endcomment %}
                </div>
            </div>
        </div>

        <div class='col p-3 col-md-6 col-lg-4'>
            <div class="card">
                <img src="{% static 'img/partners.png' %}" class="card-img-top p-3" alt="partners.png">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'about:partner_url' %}" class="card-link">Our Partners</a></h5>
                    <h6 class="card-subtitle mb-2 text-muted">Read about the great minds we are partnered with</h6>
                    <p class="card-text">We work with many prestigious names within the AI and Machine Learning domain and with many partners to help them create plans.</p>
                    {% comment %} Click here to see some of our partners! {% endcomment %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/about/history.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class='row'>
    <div class='px-5 mx-auto'>
        <img src="{% static 'img/history.png' %}" class="img-fluid" alt="{% static 'img/history.png' %}" style="max-height:350px; width:auto;">
    </div>
</div>
<div class='row'>
    <div class='col px-5'>
       {{ message }}
    </div>
</div>
{% endblock %}

templates/about/vision.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class='row'>
    <div class='px-5 mx-auto'>
        <img src="{% static 'img/DIAILogo1.png' %}" class="img-fluid" alt="{% static 'img/DIAILogo1.png' %}" style="max-height:350px; width:auto;">
    </div>
</div>
<div class='row'>
    <div class='col px-5'>
        <h4>Who are we?</h4>
        <p>We are an innovative start-up looking across multiple fields at complexity in decision making. </p>

        <p>Human decision making is heuristic – “good on average”. Artificial Intelligence only provides predictions or classifications but cant give an answer to “how to achieve your goals”.</p>

        <p>Our strategic partners are pioneers in applying “Decision Intelligence”  to complex, multi-dimensional problems.</p>


        <p>In complex circumstances you want to answer the question:</p>
        <blockquote class="blockquote">
            <p class="mb-0">”If I take this action today, what will be the outcome tomorrow”</p>
        </blockquote>
        <hr>
        At a time where “Data-led” decision making is being promoted, complexity and uncertainty have never been greater:</br>

        <ul>
            <li>Spending time on masses of data does not yield breakthrough results – typically 10% of the data has 90% of the value. Start with the decision and then select the data.</li>
            <li>And data is ”backward looking” however decisions are about a future desired state.</li>
            <li>Humans excel at causal reasoning and AI can make up for the limitations of “neurological machinery”.</li>
        </ul>

        <p>Tell us about your problem and let's figure a solution. Visit our <a href="{% url 'contact' %}">contact page</a> and let's have a chat!</p>  

    </div>
</div>
{% endblock %}