DataInnovation/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth.views import LogoutView
from django.views.generic import RedirectView

from accounts.views import LoginView, RegisterView

from home import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.home, name='home_url'),
    url(r'^news/$', views.NewsView.as_view(), name='news_url'),
    path('news/<int:pk>/', views.NewsDetailView.as_view()),
    path('news/<int:pk>/delete/', views.NewsDelete.as_view()),
    url(r'^news/create$', views.NewsRegisterView.as_view(), name='create_news'),
    path('news/<int:pk>/edit/', views.NewsDetailUpdateView.as_view(), name='edit_news'),
    path('news/<int:pk>/delete/', views.NewsDelete.as_view(), name='delete_news'),

    path('about/',include('home.urls')),
    
    url(r'^accounts/login/', RedirectView.as_view(url='/login')),
    url(r'^account/', include('accounts.urls', namespace='account')),
    url(r'^account/', include('accounts.passwords.urls')),

    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),

    url(r'^contact/', views.contact, name='contact'),  
    
] 


# if settings.DEBUG:c
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    
    url(r'^$', views.about, name='about_url'),
    url(r'^vision/', views.vision, name='vision_url'),
    url(r'^history/', views.history, name='history_url'),

    # path('<slug:element>/', views.AboutView.as_view()), # Overview of content
    # path('<slug:element>/<int:pk>/', views.AboutDetailView.as_view()), # Detail View of content
    
    url(r'^team/create/$', views.TeamRegisterView.as_view(), name='create_team'),
    path('team/', views.TeamView.as_view(), name='team_url'), # Detail View of content
    path('team/<int:pk>/', views.TeamDetailView.as_view(), name='team_detail'), # Detail View of content
    path('team/<int:pk>/edit', views.TeamDetailUpdateView.as_view(), name='edit_team'),
    path('team/<int:pk>/delete/', views.TeamDelete.as_view(), name='delete_team'),

    url(r'^solution/create$', views.SolutionRegisterView.as_view(), name='create_solution'),
    path('solution/', views.SolutionView.as_view(), name='solution_url'), # Detail View of content
    path('solution/<int:pk>/', views.SolutionDetailView.as_view(), name='solution_detail'), # Detail View of content
    path('solution/<int:pk>/edit', views.SolutionDetailUpdateView.as_view(), name='edit_solution'),
    path('solution/<int:pk>/delete/', views.SolutionDelete.as_view(), name='delete_solution'),

    url(r'^partner/create$', views.PartnerRegisterView.as_view(), name='create_partner'),
    path('partner/', views.PartnerView.as_view(), name='partner_url'), # Detail View of content
    path('partner/<int:pk>/', views.PartnerDetailView.as_view(), name='partner_detail'), # Detail View of content
    path('partner/<int:pk>/edit', views.PartnerDetailUpdateView.as_view(), name='edit_partner'),
    path('partner/<int:pk>/delete/', views.PartnerDelete.as_view(), name='delete_partner'),

    url(r'^award/create$', views.AwardRegisterView.as_view(), name='create_award'),
    path('award/', views.AwardView.as_view(), name='award_url'), # Detail View of content
    path('award/<int:pk>/', views.AwardDetailView.as_view(), name='award_detail'), # Detail View of content
    path('award/<int:pk>/edit', views.AwardDetailUpdateView.as_view(), name='edit_award'),
    path('award/<int:pk>/delete/', views.AwardDelete.as_view(), name='delete_award'),

]


# account/email/confirm/asdasfd/ -> activaiton view

templates/base/admin-tools.html
{% comment %} {% if not front %} {% endcomment %}
    <div class='row p-3'>
        <div class='col'>
            <a href="{% url edit member.id %}" class='btn btn-info' role='button'>Edit</a> 
        </div>
        <div class='col text-right'>
            <a href="{% url delete member.id %}" class='btn btn-danger' role='button'>Delete</a>
        </div>
    </div>
{% comment %} {% endif %} {% endcomment %}

templates/base/admin_create.html
<a href="{% url create %}" class='btn btn-info' role='button'><b>Create {{ element }} +</b></a></br></br>

templates/base/css.html
{% load static %}
    <link rel="icon" href="{% static 'img/favicon.png'%}">
<!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
<!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

<!-- Jquery confirm -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">

<!-- Customizing font Style CSS -->
    <link rel="stylesheet" href="{% static 'css/fonts.css' %}">

<!-- Custom Social Media button styles -->
    <link rel="stylesheet" href="{% static 'css/social-buttons.css' %}">

templates/base/delete_view.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %} 
        <p>Are you sure you want to delete <b>"{{ object }}"</b>?</p> 
        <input type="submit" value="Confirm"> 
    </form> 
{% endblock %}

templates/base/footer.html
</br></br></br></br></br>
<div class='fixed-bottom p-3 bg-dark text-white'>
    <div class='row'>
        <div class='col'>
            <a href="mailto:enquiries@datainnovation.ai" class="scl-btn shadow fas fa-envelope"></a>
            <a href="https://www.linkedin.com/company/data-innovation-ai/" class="scl-btn shadow fab fa-linkedin-in"></a>
        </div>
        <div class='col text-right my-auto'>
            {% if user.is_authenticated %}
                <a class="text-white" href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a class="text-white" href="{% url 'login' %}">Login</a>
            {% endif %}            
        </div>
    </div>
</div>

templates/base/forms.html
<div class='col-12 mx-auto'>
    <form class='contact-form' method='POST' action="{% url 'contact' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type='submit' class='btn btn-secondary'>Submit</button>
    </form>
</div>

templates/base/js.html
{% load static %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS 
slim is a slimmed down version of JS -->
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

<!-- Jquery-confirm JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>

<!-- js Render -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/1.0.2/jsrender.min.js"></script>

<!-- Django Secure AJAX-->
<script src='{% static "js/csrf.ajax.js" %}'></script>

<!-- Contact Form -->
<script src='{% static "js/contact.js" %}'></script>

templates/base/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3 shadow">
    <div class='container'>
        <a class="navbar-brand" href="{% url 'home_url' %}">

            <img src="{% static 'img/DIAILogo1.png' %}" width="60" height="45" alt="{% static 'img/DataInnovationAI_Logo1.png' %}">
            <b>
                <span style="font-size:14.0pt;line-height:107%;font-family:'Quicksand',serif;color:#548235;mso-themecolor:accent6;mso-themeshade:191;mso-style-textfill-fill-color:#548235;mso-style-textfill-fill-themecolor:accent6;
                    mso-style-textfill-fill-alpha:100.0%;mso-style-textfill-fill-colortransforms:lumm=75000">Data</span> 

                <span style="font-size:14.0pt;line-height:107%;font-family:'Quicksand',serif;color:#2F5597;mso-themecolor:accent1;mso-themeshade:191;mso-style-textfill-fill-color:#2F5597;mso-style-textfill-fill-themecolor:accent1;
                    mso-style-textfill-fill-alpha:100.0%;mso-style-textfill-fill-colortransforms:lumm=75000">Innovation.AI</span>
            </b>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == home_url %} active {% endif %}">
                    <a class="nav-link" href="{% url 'home_url' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <!-- <li class="nav-item {% if request.path == rss_url %} active {% endif %}">
                    <a class="nav-link" href="{{ rss_url}}">RSS Feed</a>
                </li> -->
                <li class="nav-item {% if request.path == about_url %} active {% endif %}">
                    <a class="nav-link" href="{% url 'about:about_url' %}">About</a>
                </li>
                
                {% if request.user.is_authenticated %}
                <li>
                    <div class = "dropdown show">
                        <a class="mt-0 btn btn-secondary dropdown-toggle" href="#" title="About us" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Manage Site
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'create_news' %}">Write a News Post</a>
                            <a class="dropdown-item" href="{% url 'about:create_team' %}">Add a Team Member</a>
                            <a class="dropdown-item" href="{% url 'about:create_solution' %}">Add a Solution</a>
                            <a class="dropdown-item" href="{% url 'about:create_partner' %}">Add a Partner</a>
                            <a class="dropdown-item" href="{% url 'about:create_award' %}">Add an Award</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>            
                        </div>
                    </div>
                </li>
                {% endif %}

                <li class="nav-item {% if request.path == news_url %} active {% endif %}">
                    <a class="nav-link" href="{% url 'news_url' %}">News</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact' %}">Contact</a>
                </li>

                {% comment %} {% if request.user.is_authenticated %}
                <li class="nav-item {% if request.path == logout_url %} active {% endif %}">
                    <a class="dropdown-item" href="{{ logout_url }}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item {% if request.path == register_url %} active {% endif %}">
                    <a class="nav-link" href="{{ register_url }}">Register</a>
                </li>
                <li class="nav-item {% if request.path == login_url %} active {% endif %}">
                    <a class="nav-link" href="{{ login_url }}">Login</a>
                </li>
                {% endif %}                      {% endcomment %}
                <!--    

                -->

            </ul>
                
        </div>
    </div>
</nav>