DataInnovation/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth.views import LogoutView
from django.views.generic import RedirectView

from accounts.views import LoginView, RegisterView

from home import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.home, name='home_url'),
    url(r'^news/$', views.NewsView.as_view(), name='news_url'),
    path('news/<int:pk>/', views.NewsDetailView.as_view()),
    path('news/<int:pk>/delete/', views.NewsDelete.as_view()),
    url(r'^news/create$', views.NewsRegisterView.as_view(), name='create_news'),
    path('news/<int:pk>/edit/', views.NewsDetailUpdateView.as_view(), name='edit_news'),
    path('news/<int:pk>/delete/', views.NewsDelete.as_view(), name='delete_news'),

    path('about/',include('home.urls')),
    
    url(r'^accounts/login/', RedirectView.as_view(url='/login')),
    url(r'^account/', include('accounts.urls', namespace='account')),
    url(r'^account/', include('accounts.passwords.urls')),

    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),

    url(r'^contact/', views.contact, name='contact'),  
    
] 


# if settings.DEBUG:c
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/passwords/urls.py
# accounts.passwords.urls.py 
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns  = [
    url(r'^password/change/$', 
            auth_views.PasswordChangeView.as_view(), 
            name='password_change'),
    url(r'^password/change/done/$',
            auth_views.PasswordChangeDoneView.as_view(), 
            name='password_change_done'),
    url(r'^password/reset/$', 
            auth_views.PasswordResetView.as_view(), 
            name='password_reset'),
    url(r'^password/reset/done/$', 
            auth_views.PasswordResetDoneView.as_view(), 
            name='password_reset_done'),
    url(r'^password/reset/\
            (?P<uidb64>[0-9A-Za-z_\-]+)/\
            (?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
            auth_views.PasswordResetConfirmView.as_view(), 
            name='password_reset_confirm'),

    url(r'^password/reset/complete/$', 
            auth_views.PasswordResetCompleteView.as_view(), 
            name='password_reset_complete'),
]

accounts/urls.py
from django.conf.urls import url
from django.urls import path

from .views import (
    AccountHomeView,
    AccountEmailActivationView,
    UserDetailUpdateView,
) 

app_name = 'accounts'

urlpatterns = [
    url(r'^$', AccountHomeView.as_view(), name='home'),
    url(r'^details/$', UserDetailUpdateView.as_view(), name='user-update'),
    url(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', AccountEmailActivationView.as_view(), name='email-activate'),
    url(r'^email/resend-activation/$', AccountEmailActivationView.as_view(), name='resend-activation'),
]


# account/email/confirm/asdasfd/ -> activaiton view

home/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    
    url(r'^$', views.about, name='about_url'),
    url(r'^vision/', views.vision, name='vision_url'),
    url(r'^history/', views.history, name='history_url'),

    # path('<slug:element>/', views.AboutView.as_view()), # Overview of content
    # path('<slug:element>/<int:pk>/', views.AboutDetailView.as_view()), # Detail View of content
    
    url(r'^team/create/$', views.TeamRegisterView.as_view(), name='create_team'),
    path('team/', views.TeamView.as_view(), name='team_url'), # Detail View of content
    path('team/<int:pk>/', views.TeamDetailView.as_view(), name='team_detail'), # Detail View of content
    path('team/<int:pk>/edit', views.TeamDetailUpdateView.as_view(), name='edit_team'),
    path('team/<int:pk>/delete/', views.TeamDelete.as_view(), name='delete_team'),

    url(r'^solution/create$', views.SolutionRegisterView.as_view(), name='create_solution'),
    path('solution/', views.SolutionView.as_view(), name='solution_url'), # Detail View of content
    path('solution/<int:pk>/', views.SolutionDetailView.as_view(), name='solution_detail'), # Detail View of content
    path('solution/<int:pk>/edit', views.SolutionDetailUpdateView.as_view(), name='edit_solution'),
    path('solution/<int:pk>/delete/', views.SolutionDelete.as_view(), name='delete_solution'),

    url(r'^partner/create$', views.PartnerRegisterView.as_view(), name='create_partner'),
    path('partner/', views.PartnerView.as_view(), name='partner_url'), # Detail View of content
    path('partner/<int:pk>/', views.PartnerDetailView.as_view(), name='partner_detail'), # Detail View of content
    path('partner/<int:pk>/edit', views.PartnerDetailUpdateView.as_view(), name='edit_partner'),
    path('partner/<int:pk>/delete/', views.PartnerDelete.as_view(), name='delete_partner'),

    url(r'^award/create$', views.AwardRegisterView.as_view(), name='create_award'),
    path('award/', views.AwardView.as_view(), name='award_url'), # Detail View of content
    path('award/<int:pk>/', views.AwardDetailView.as_view(), name='award_detail'), # Detail View of content
    path('award/<int:pk>/edit', views.AwardDetailUpdateView.as_view(), name='edit_award'),
    path('award/<int:pk>/delete/', views.AwardDelete.as_view(), name='delete_award'),

]


# account/email/confirm/asdasfd/ -> activaiton view

accounts/views.py
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.utils.safestring import mark_safe
from django.views.generic import CreateView, FormView, DetailView, View, UpdateView
from django.views.generic.edit import FormMixin

from .forms import LoginForm, RegisterForm, GuestForm, ReactivateEmailForm, UserDetailChangeForm, TeamRegisterForm, TeamDetailChangeForm
from .models import GuestEmail, EmailActivation
from .signals import user_logged_in

from home.models import Team

from DataInnovation.mixins import NextUrlMixin, RequestFormAttachedMixin

# @login_required #/automatically goes to accounts/login/?next=/some/path/
# def account_home_view(request):
# 	return render(request, 'accounts/home.html', {})

class AccountHomeView(LoginRequiredMixin, DetailView):
	template_name = 'accounts/home.html'
	def get_object(self):
		return self.request.user

class AccountEmailActivationView(FormMixin, View):
	success_url = '/login/'
	form_class = ReactivateEmailForm

	def get(self, request, key=None, *args, **kwargs):
		self.key = key
		if key is not None:
			qs = EmailActivation.objects.filter(key__iexact=key)
			confirm_qs = qs.confirmable()
			if confirm_qs.count() == 1:
				obj = confirm_qs.first()
				obj.activate()
				messages.success(request, "Your email has been confirmed. Please login.")
				return redirect('login')
			else:
				activated_qs = qs.filter(activated=True)
				if activated_qs.exists():
					reset_link=reverse('password_reset')
					msg = """Your email has already been confirmed
					Do you need to <a href="{link}">reset your password</a>?
					""".format(link=reset_link)
					messages.success(request, mark_safe(msg))
					return redirect('login')
		context = {'form':self.get_form(), 'key': key}
		return render(request, 'registration/activation-error.html', context)

	def post(self, request, *args, **kwargs):
		form = self.get_form()
		if form.is_valid():
			return self.form_valid(form)
		else:
			return self.form_invalid(form)

	def form_valid(self, form):
		msg = """Activation link sent, please check your email."""
		request = self.request
		messages.success(request, msg)
		email = form.cleaned_data.get('email')
		obj = EmailActivation.objects.email_exists(email).first()
		user = obj.user
		new_activation = EmailActivation.objects.create(user=user, email=email)
		new_activation.send_activation()
		return super(AccountEmailActivationView, self).form_valid(form)
	
	def form_invalid(self, form):
		context = {'form':form, 'key': self.key}
		return render(self.request, 'registration/activation-error.html', context)

class GuestRegisterView(NextUrlMixin, RequestFormAttachedMixin, CreateView):
	form_class = GuestForm
	default_next = '/register/'

	def get_success_url(self):
		return self.get_next_url()

	def form_invalid(self, form):
		return redirect(self.default_next)

class LoginView(NextUrlMixin, RequestFormAttachedMixin, FormView):
	form_class = LoginForm
	success_url = '/'
	template_name = 'accounts/login.html'
	default_next = '/'

	def form_valid(self, form):
		next_path = self.get_next_url()
		return redirect(next_path)

class RegisterView(CreateView):
	form_class = RegisterForm
	template_name = 'accounts/register.html'
	success_url = '/login/'

	@method_decorator(login_required) # Make sure user is logged in   
	def dispatch(self, *args, **kwargs):
		return super().dispatch(*args, **kwargs)

class TeamRegisterView(LoginRequiredMixin, CreateView):
	form_class = TeamRegisterForm
	template_name = 'accounts/member-register.html'
	success_url = '/account/'

	@method_decorator(login_required) # Make sure user is logged in   
	def dispatch(self, *args, **kwargs):
		return super().dispatch(*args, **kwargs)

class TeamDetailUpdateView(LoginRequiredMixin, UpdateView):
	form_class = TeamDetailChangeForm
	template_name = 'accounts/team-detail-update-form.html'
	success_url = '/account/'

	def get_object(self):
		pk = self.kwargs.get(self.pk_url_kwarg)
		print(pk)
		return Team.objects.get(pk=pk)

	def get_context_data(self, *args, **kwargs):
		context = super(TeamDetailUpdateView, self).get_context_data(*args, **kwargs)
		# print(context)
		context['title'] = 'Change your account details'
		return context

		# {
		# 	'object': <SimpleLazyObject: <User: admin>>, 
		# 	'user': <SimpleLazyObject: <User: admin>>, 
		# 	'form': <TeamDetailChangeForm bound=False, valid=Unknown, fields=(name)>, 
		# 	'view': <accounts.views.TeamDetailUpdateView object at 0x0000017EBF7E32B0>
		# }
	def get_success_url(self):
		return reverse('account:home')


class UserDetailUpdateView(LoginRequiredMixin, UpdateView):
	form_class = UserDetailChangeForm
	template_name = 'accounts/detail-update-form.html'
	success_url = '/account/'

	def get_object(self):
		return self.request.user

	def get_context_data(self, *args, **kwargs):
		context = super(UserDetailUpdateView, self).get_context_data(*args, **kwargs)
		context['title'] = 'Change your account details'
		return context
	
	def get_success_url(self):
		return reverse('account:home')

###

# def login_page(request):
# 	form = LoginForm(request.POST or None)
# 	context = {
# 		"form": form,
# 	}
	# next_ = request.GET.get('next')
	# next_post = request.POST.get('next')
	# redirect_path = next_ or next_post or None
# 	if form.is_valid():
# 		username = form.cleaned_data.get("username")
# 		password = form.cleaned_data.get("password")
# 		user = authenticate(request, username=username, password=password)

# 		if user is not None:
# 			login(request, user)
# 			try:
# 				del request.session['guest_email_id']
# 			except:
# 				pass
# 			if is_safe_url(redirect_path, request.get_host()):
# 				return redirect(redirect_path)
# 			else:
# 				return redirect("/")
# 		else:
# 			# Return an 'invalid login' error message.
# 			print("Error")

	# return render(request, "accounts/login.html", context)

# User = get_user_model()
# def register_page(request):
# 	form = RegisterForm(request.POST or None)
# 	context = {
# 		"form": form,
# 	}
# 	if form.is_valid():
# 		form.save()
# 		# print(form.cleaned_data)
# 		# username = form.cleaned_data.get("username")
# 		# email = form.cleaned_data.get("email")
# 		# password = form.cleaned_data.get("password")
# 		# new_user = User.objects.create_user(username, email, password)
# 		# print(new_user)

# 	return render(request, "accounts/register.html", context)

accounts/templates/accounts/detail-update-form.html
{% extends "base.html" %}

{% block content %}
<div class='col-12 col-md-6 mx-auto'>
    {% if title %}
    <h1 class='my-3'>{{ title }}</h1>
    {% endif %}
    <form method='POST' action='{% if action_url %}{{action_url}}{% endif %}'>
        {% csrf_token %}
        {% if next_url %}
        <input type='hidden' name='next' value='{{ next_url }}'>
        {% endif %}
        {{ form.as_p }}
        <label for='email'>Email</label>
        <input type='text' class='form-control disabled' value='{{ request.user.email }}' disabled="disabled"/>
        <span class='help-text'>Cannot change email</span><br/>
        <button class='btn btn-secondary my-3' type='submit'>Submit</button>
        <a href="{% url 'password_change' %}">Change Password</a>
    </form>

</div>
{% endblock %}

accounts/templates/accounts/home.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Content Management</h1>
            <hr/>
        </div>
    </div>
    <div class='row'>
        <div class='col'>
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">About</h5>
                    <a class='list-group-item' href='#'>Manage Team</a>
                    <a class='list-group-item' href='#'>Manage Solutions</a>
                    <a class='list-group-item' href='#'>Manage Awards</a>
                    <a class='list-group-item' href='#'>Manage Partners</a>
                </div>
            </div>
        </div>
        <div class='col'>
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">News</h5>
                    <div class='list-group'>
                        <a class='list-group-item' href="{% url 'about:create_news' %}">Create News Post</a>
                        <a class='list-group-item' href="{% url 'about:create_solution' %}">Create  News</a>
                    </div>
                </div>
            </div>
        </div>
        <div class='col'>
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Messages</h5>
                    <div class='list-group'>
                        <a class='list-group-item' href="{% url 'about_url' %}">Read Messages</a>
                        {% comment %} <a class='list-group-item' href="{% url 'about_url' %}">Manage News</a> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	<h1>Login</h1>
	<div class='container'>
		<div class='row'>
			<div class='col-6'>
				<div class='col-md-6 col-12 mx-auto'>
					<form method='POST'>
						{% csrf_token %}
						{{ form.as_p }}
						<button type='submit' class='btn btn-secondary'>Submit</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

accounts/templates/accounts/member-register.html
{% extends "base.html" %}

{% block content %}
	<div class='container'>
		<div class='row'>
			<div class='col-6 mx-auto'>
				<h1>Register</h1>
				<p>Register new members to the team to be displayed on the Our Team page.</p>
				<hr class='divider'>
				<div class='col-md-6 col-12 mx-auto'>
					<form method='POST'>
						{% csrf_token %}
						{% include 'accounts/snippets/form.html'%}
						{% comment %} <button type='submit' class='btn btn-secondary'>Submit</button> {% endcomment %}
					</form></br>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block content %}
	<div class='container'>
		<div class='row'>
			<div class='col-6 mx-auto'>
				<h1>Register</h1>
				<p>Register new members to the team to be displayed on the Our Team page.</p>
				<hr class='divider'>
				<div class='col-md-6 col-12 mx-auto'>
					<form method='POST'>
						{% csrf_token %}
						{{ form.non_field_errors }}
						<div class="fieldWrapper">
							{{ form.username.errors }}
							<label for="{{ form.username.id_for_label }}">Username:</label></br>
							{{ form.username }}
						</div>
						<div class="fieldWrapper">
							{{ form.first_name.errors }}
							<label for="{{ form.first_name.id_for_label }}">First Name:</label></br>
							{{ form.first_name }}
						</div>
						<div class="fieldWrapper">
							{{ form.last_name.errors }}
							<label for="{{ form.last_name.id_for_label }}">Last Name:</label></br>
							{{ form.last_name }}
						</div>
						<div class="fieldWrapper">
							{{ form.email.errors }}
							<label for="{{ form.email.id_for_label }}">Email:</label></br>
							{{ form.email }}
						</div>
						<div class="fieldWrapper">
							{{ form.password1.errors }}
							<label for="{{ form.password1.id_for_label }}">Password:</label></br>
							{{ form.password1 }}
						</div>
						<div class="fieldWrapper">
							{{ form.password2.errors }}
							<label for="{{ form.password2.id_for_label }}">Confirm Password:</label></br>
							{{ form.password2 }}
						</div></br>
						<button type='submit' class='btn btn-secondary'>Submit</button>
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

accounts/templates/accounts/team-detail-update-form.html
{% extends "base.html" %}

{% block content %}
<div class='col-12 col-md-6 mx-auto'>
    {% if title %}
    <h1 class='my-3'>{{ title }}</h1>
    {% endif %}
    <form method='POST' action='{% if action_url %}{{action_url}}{% endif %}'>
        {% csrf_token %}
        {% if next_url %}
        <input type='hidden' name='next' value='{{ next_url }}'>
        {% endif %}
        {{ form.as_p }}
        <button class='btn btn-secondary my-3' type='submit'>Submit</button>
    </form>

</div>
{% endblock %}

accounts/templates/accounts/user_detail.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-3 non d-md-block bg-light sidebar">
            <div class="card">
                <img src="{% if user.media_thumbnail %}{{user.media_thumbnail}}{% else %}{% static 'img/CorvusCorax.png' %}{% endif %}" class="rounded align-self-center" style="width: 90%" alt="">
                <div class="card-body">
                    {{ user.id }} - {{ user.username }}{% if user.admin %} <strong>[Admin]</strong> {% endif %}( <span class="text-danger">{{ entry.score_up }}0</span> | <span class="text-primary">{{ entry.score_down }}0</span> ) </br>
                    <small class="m-0 p-0">
                    Account created {{ user.timestamp }} </br>
                        <em>{{ entry.published|date:'D, Y M d H:i:s T' }}</em></br>
                        <p class="card-text m-0 p-0">{{ entry.summary }}Add User Quotes?</p>
                    </small></br>
                </div>
            </div>
        </nav>

        <main role="main" class="col-md-8 ml-sm-auto col-lg-9 px-4">
            {% for comment in comments %}
            {% include 'rss/profile-comments.html' with entry=comment.entry %}</br>
            </hr>
            {% endfor %}
        </main>
    </div>
</div>
 

{% endblock %}